### PR TITLE
JSON arrays -> Lisp vectors

### PR DESCRIPTION
**Pull request by aartaka**
This introduces quite a radical change: JSON arrays are now decoded as Lisp vectors. This is to make NJSON much more consistent and keep the promise of type disjoint decoding:
- Before this change, both `[]` and `false` were decoded as NIL. Which meant: `typecase`-ing over the NJSON values would've been slightly (and unnoticeably!) broken.
- This change fixes the equivocal NIL by decoding empty JSON arrays as `#()`, and `false` as NIL (as before).

# Discussion

- Should major version number be bumped up? This is a backwards-incompatible change, after all.
  - But then, all the helpers used specialize against the ambiguous `sequence`, so, technically, we're not breaking anything, because `sequence`-specific operations are array-like in general. No `nthcdr` etc.
  - If we bump the version up, then we can finally remove the `get_` and other deprecated functions/macros.
- This change makes our decoding of arrays harder to work with, compared to lists, which are ~more equal than others~ the most polished part of any Lisp. Should we be more lenient and allow specialization of array decoding maybe? That would break the disjoint types guarantee, though.

### CODE REVIEW

**Comment by aartaka** [comment]
Hmmm, that's strange. Tests fail with `#(1 2 3 "hello")` not being equal `#(1 2 3 "hello")` \~_\~

**Comment by aartaka** [comment]
@Ambrevar, @aadcg, any feedback? Is it too radical? Is it just what we need? Is this backward-incompatibility not in line with Nyxt 3.0 cleanups?

**Comment by aadcg** [comment]
I don't know what are the implication of this change for Nyxt. Perhaps an example would help!

@Ambrevar might have a deeper understanding on this topic.

**Comment by Ambrevar** [comment]
I don't have a strong opinion, the original post phrases the pros and cons very very, and making arrays optional has pros and cons itself, like Artyom mentioned, which makes all this a bit tricky to judge.

Hmmm... What about a separate package, this way each package has their own guarantees?

**Comment by aadcg** [comment]
Thanks @Ambrevar. I've re-read the top post. No strong opinion from my side.

**Comment by aartaka** [comment]
> Hmmm... What about a separate package, this way each package has their own guarantees?

Not sure that'd be good, because then the default NJSON would still be inconsistent with its promises of disjoint types by default :)

**Comment by Ambrevar** [comment]
You could change the default JSON to offer disjoint types, and add a package with joint types.

**Comment by aartaka** [comment]
Oh, right. Sounds like a plan then!

**Comment by aartaka** [comment]
I'm terribly sorry about the back-and-forth that I'm doing on this PR, but it seems that supporting two representations makes cl-json port (and any port based on any JSON library allowing two representations) extremely bloated, with either redefining all methods or providing `json:*json-array-type*` explicitly in every function.

So I'm leaning more and more to breaking the backwards-compatibility in one single patch, including:
- Vector decoding.
- Removal of `_*` functions/macros.
- Addition of `jzon` (https://github.com/Zulu-Inuoe/jzon) as the alternative (default?) parser.
- Additional `jget`/`jrem` specializers with JSON pointers (https://www.rfc-editor.org/rfc/rfc6901). Backwards-incompatible due to changing semantics of `jget` etc. indexing by strings.

**Comment by Ambrevar** [comment]
Let me know when this is ready for review.

**Comment by aartaka** [comment]
Closing in favor of #6

**Pull request closed without merging**
