### PR TITLE
Fix nasdf compilation test

### PR DESCRIPTION
**Pull request by Ambrevar**

### CODE REVIEW

**Comment by Ambrevar** [comment]
I'm puzzled: the compilation tests pass (https://github.com/atlas-engineer/njson/actions/runs/3995712213/jobs/6854898110) despite commit https://github.com/atlas-engineer/njson/pull/2/commits/87b4b9f434babd57edd17623cfd64c4424529ed6.

@aartaka Any idea?

**Comment by aartaka** [comment]
Could it be https://github.com/atlas-engineer/ntemplate/issues/9 ?

**Comment by aartaka** [comment]
Oh, right, it should be fixed with [7e61c37](https://github.com/atlas-engineer/njson/pull/2/commits/7e61c377e359327470dc75f1102d5032c21b0077)...

**Comment by Ambrevar** [comment]
That's the thing, the compilation tests _do pass_! ?!?

**Comment by aartaka** [comment]
Oh wow, lots of stuff :D Thanks for fixing it, Pierre!

**Pull request merged**
